Move config from `packages.yml` to `main_config.yml` | add `install coc.nvim` step

diff --git a/main_config.yml b/main_config.yml
--- a/main_config.yml
+++ b/main_config.yml
@@ -42,3 +42,50 @@
         state: present
         line: "/home/{{ exec_username }}/.xmonad/scripts/screen_setup.sh"
 
+    - name: set fish as default shell
+      become: yes
+      user: 
+        name: "{{ exec_username }}"
+        shell: /usr/bin/fish
+
+    - name: install Plug for nvim
+      shell:  |
+        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
+             https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
+
+    - name: install plugins for nvim
+      shell: |
+        nvim +PlugInstall +qa
+
+    - name: install coc.nvim
+      shell: |
+        set -o nounset    # error when referencing undefined variable
+        set -o errexit    # exit when command fails
+
+        # Install latest nodejs
+        if [ ! -x "$(command -v node)" ]; then
+            curl --fail -LSs https://install-node.now.sh/latest | sh
+            export PATH="/usr/local/bin/:$PATH"
+        fi
+
+        # Use package feature to install coc.nvim
+
+        # for neovim
+        mkdir -p ~/.local/share/nvim/site/pack/coc/start
+        cd ~/.local/share/nvim/site/pack/coc/start
+        curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz | tar xzfv -
+
+        # Install extensions
+        mkdir -p ~/.config/coc/extensions
+        cd ~/.config/coc/extensions
+        if [ ! -f package.json ]
+        then
+          echo '{"dependencies":{}}'> package.json
+        fi
+        # Change extension names to the extensions you need
+        npm install coc-snippets --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+        npm install coc-tabnine --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+        npm install coc-python --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+        npm install coc-rust-analyzer --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+        npm install coc-clangd --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+
