new GitHub ssh key | WiP

diff --git a/roles/config/tasks/main.yml b/roles/config/tasks/main.yml
--- a/roles/config/tasks/main.yml
+++ b/roles/config/tasks/main.yml
@@ -4,27 +4,27 @@
     known_hosts:
       path: /etc/ssh/ssh_known_hosts
       name: github.com
-      key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
+      key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
 
-  - name: check if dotfiles cloned
-    git:
-      repo: 'https://github.com/przempore/.dotfiles.git'
-      dest: "/home/{{ ansible_user }}/.dotfiles"
-      clone: no
-      update: no
-    register: dotfiles_cloned
+  # - name: check if dotfiles cloned
+  #   git:
+  #     repo: 'https://github.com/przempore/.dotfiles.git'
+  #     dest: "/home/{{ ansible_user }}/.dotfiles"
+  #     clone: no
+  #     update: no
+  #   register: dotfiles_cloned
 
-  - name: show `dotfiles_cloned`
-    debug:
-      var: dotfiles_cloned
+  # - name: show `dotfiles_cloned`
+  #   debug:
+  #     var: dotfiles_cloned
 
-  - name: download dotfiles
-    git:
-      repo: 'https://github.com/przempore/.dotfiles.git'
-      dest: "/home/{{ ansible_user }}/.dotfiles"
-      recursive: yes
-      update: yes
-    when: dotfiles_cloned['changed'] != false
+  # - name: download dotfiles
+  #   git:
+  #     repo: 'git@github.com:przempore/.dotfiles.git'
+  #     dest: "/home/{{ ansible_user }}/.dotfiles"
+  #     # recursive: yes
+  #     update: yes
+  #   # when: dotfiles_cloned['changed'] != false
 
   - name: run stow on .dotfiles
     shell: |
@@ -47,10 +47,10 @@
       cd .dotfiles
       git checkout .
 
-  - name: config `mpv` player
-    shell: |
-      cp /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/mpv-youtube-quality/youtube-quality.lua /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/scripts/
-      cp /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/mpv-youtube-quality/youtube-quality.conf /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/script-opts/
+  # - name: config `mpv` player
+  #   shell: |
+  #     cp /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/mpv-youtube-quality/youtube-quality.lua /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/scripts/
+  #     cp /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/mpv-youtube-quality/youtube-quality.conf /home/{{ ansible_user }}/.dotfiles/mpv/.config/mpv/script-opts/
 
   - name: set fish as default shell
     become: yes
@@ -58,41 +58,41 @@
       name: "{{ ansible_user }}"
       shell: /usr/bin/fish
 
-  - name: install Plug for nvim
-    shell:  |
-      sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
-           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
+  # - name: install Plug for nvim
+  #   shell:  |
+  #     sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
+  #          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
 
-  - name: install plugins for nvim
-    shell: |
-      nvim --headless +PlugInstall +qa
-      nvim +CocCommand clangd.install +qa
-
-  - name: install coc.nvim
-    shell: |
-      set -o nounset    # error when referencing undefined variable
-      set -o errexit    # exit when command fails
-
-      # Use package feature to install coc.nvim
-
-      # for neovim
-      mkdir -p ~/.local/share/nvim/site/pack/coc/start
-      cd ~/.local/share/nvim/site/pack/coc/start
-      curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz | tar xzfv -
-
-      # Install extensions
-      mkdir -p ~/.config/coc/extensions
-      cd ~/.config/coc/extensions
-      if [ ! -f package.json ]
-      then
-        echo '{"dependencies":{}}'> package.json
-      fi
-      # Change extension names to the extensions you need
-      npm install coc-snippets --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
-      npm install coc-tabnine --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
-      npm install coc-python --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
-      npm install coc-rust-analyzer --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
-      npm install coc-clangd --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+  # - name: install plugins for nvim
+  #   shell: |
+  #     nvim --headless +PlugInstall +qa
+  #     nvim +CocCommand clangd.install +qa
+  #
+  # - name: install coc.nvim
+  #   shell: |
+  #     set -o nounset    # error when referencing undefined variable
+  #     set -o errexit    # exit when command fails
+  #
+  #     # Use package feature to install coc.nvim
+  #
+  #     # for neovim
+  #     mkdir -p ~/.local/share/nvim/site/pack/coc/start
+  #     cd ~/.local/share/nvim/site/pack/coc/start
+  #     curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz | tar xzfv -
+  #
+  #     # Install extensions
+  #     mkdir -p ~/.config/coc/extensions
+  #     cd ~/.config/coc/extensions
+  #     if [ ! -f package.json ]
+  #     then
+  #       echo '{"dependencies":{}}'> package.json
+  #     fi
+  #     # Change extension names to the extensions you need
+  #     npm install coc-snippets --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+  #     npm install coc-tabnine --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+  #     npm install coc-python --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+  #     npm install coc-rust-analyzer --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
+  #     npm install coc-clangd --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
 
   - name: Reboot
     become: yes
